version: '3.8'

services:
  mysql:
    container_name: mysql_local
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d # MySQL 설정 파일을 위한 볼륨
      - ./db/initdb.d:/docker-entrypoint-initdb.d # 초기화 스크립트를 위한 볼륨
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local
      - MYSQL_PASSWORD=hooney1108!
      - TZ=Asia/Seoul