spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: pass_local
#    password: passlocal123
#    driver-class-name: org.h2.Driver

  datasource:
    url: jdbc:mysql://localhost:13306/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: pass_local
    password: hooney1108!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20

  batch:
    jdbc:
      initialize-schema: always
    job.enabled: true

