spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: pass_local
    password: passlocal123
    driver-class-name: org.h2.Driver

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:13306/pass_local
#    username: pass_local
#    password: hooney1108!
#    driver-class-name: com.mysql.cj.jdbc.Driver

